# -*- coding: utf-8 -*-
"""ML_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqxrA0osRJposT0G8KA0urU-_cvrnAoh
"""

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data -O /content/iris.csv

import numpy as np

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv('/content/iris.csv', header=None)
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
print("Dataset loaded successfully. Columns are:")
print(df.columns)

display(df.head())

print("\nMissing values:")
print(df.isnull().sum())

sns.pairplot(df, hue='species')
plt.suptitle("Pairplot of Iris Dataset", y=1.02)
plt.show()

plt.figure(figsize=(10, 6))
df.drop('species', axis=1).boxplot()
plt.title("Boxplot of Features")
plt.show()

#BOX PLOT
for col in df.columns[:-1]:  # Exclude target
    sns.boxplot(x='species', y=col, data=df)
    plt.title(f'Boxplot of {col} by Target')
    plt.show()

plt.figure(figsize=(8, 5))
sns.heatmap(df.drop('species', axis=1).corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

X = df.drop('species', axis=1)
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

k_values = [1, 3, 5, 7]
cv_scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X, y, cv=5)
    cv_scores.append(scores.mean())
    print(f"k={k} -> Cross-validation Accuracy: {scores.mean():.4f}")

# Plot accuracy vs k
plt.figure(figsize=(8, 5))
plt.plot(k_values, cv_scores, marker='o')
plt.title('k-NN Accuracy for different k values (5-fold CV)')
plt.xlabel('Number of Neighbors (k)')
plt.ylabel('Cross-validation Accuracy')
plt.grid(True)
plt.show()

# Final model with best k
best_k = k_values[np.argmax(cv_scores)]
print(f"Best k from CV: {best_k}")
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train, y_train)
y_pred = knn_best.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("\nTest Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))